[17기 양한아] 장바구니 및 결제 기능 구현
wecode-bootcamp-korea/17-1st-TEAMCOOP-backend pull request #8
Opened 2021-02-23 17:23 UTC by yangahh

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약

		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 로그인 한 사용자만 장바구니 기능 사용 가능
- 장바구니 페이지 기능 구현 (CartView)
- 장바구니에 담긴 상품의 수량, 사이즈 변경 (CartDetailView)
- 장바구니에 담긴 상품 삭제 기능 구현 (CartDetailView)
- 결제 페이지 구현 (CheckOutView)
- 결제 기능 구현 (CheckOutView)

## 기타 질문 및 특이 사항
- 변수 네이밍이 너무 힘들어요
- 어떻게 하면 코드를 깔끔하고 가독성 있게 쓸 수 있을지 고민을 해봐야 할 것 같습니다.

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-02-24 02:34 UTC, jamessoun93 commented
한아님 라벨 추가해주세요~

2021-02-25 10:07 UTC, Kang-kyunghun requested changes

2021-02-25 10:07 UTC, Kang-kyunghun commented on order/views.py
> +        zipcode_order  = data.get('zipcode', None)
필수로 들어와야 하는 값은 data['key']로 받은 뒤에 해당 key가 안 들어왔을 때 try except로 처리해 주세요.

2021-02-25 10:07 UTC, Kang-kyunghun commented on order/views.py
> +        order_info = Order.objects.get(order_number=order_number)
objects.get() 사용했을 떄 나올 수 있는 에러 또한 에러처리 해주세요.

2021-02-25 10:07 UTC, Kang-kyunghun commented on order/views.py
> +        order_info.order_status_id = 2
하드코딩 말고, 상수를 만들어서 수정해 주세요.

2021-02-25 10:07 UTC, Kang-kyunghun commented on order/views.py
> +        order_info     = Order.objects.get(order_number=order_number)
objects.get()에 대한 예외 처리 헤주세요.

2021-02-25 10:07 UTC, Kang-kyunghun commented on order/views.py
> +            cart_product_list.append(product_info)
list comprehension으로 바꿔 주세요.

2021-02-25 10:07 UTC, Kang-kyunghun commented on order/views.py
> +        if not order_number:
key error try except로 바꿔 주세요.

2021-02-25 10:07 UTC, Kang-kyunghun commented on order/views.py
> +        order_exist   = Order.objects.get(user=user, order_status_id=1)
하드 코딩 수정해 주세요.

2021-02-25 10:07 UTC, Kang-kyunghun commented on order/views.py
> +    def post(self, request, product_stock_id):
patch로 수정해 주세요.

2021-02-25 10:07 UTC, Kang-kyunghun commented on order/views.py
> +            cart_product_list.append(product_info)
list comprehension 바꿔 주세요.

2021-02-25 10:07 UTC, Kang-kyunghun commented on order/views.py
> +        order_exist          = Order.objects.get(user=user, order_status_id=1)
하드 코딩 수정해 주세요.

2021-02-25 11:23 UTC, Kang-kyunghun requested changes

2021-02-25 11:23 UTC, Kang-kyunghun commented on order/urls.py
> +    path('/cart/<int:product_stock_id>', CartDetailView.as_view()),
```suggestion
    path('/cart', CartView.as_view()),
    path('/cart/<int:product_stock_id>', CarView.as_view()),
```

2021-02-25 18:29 UTC, yangahh commented on order/views.py
> +        zipcode_order  = data.get('zipcode', None)
수정했습니다~

2021-02-25 18:29 UTC, yangahh commented on order/views.py
> +        order_info = Order.objects.get(order_number=order_number)
네 에러처리 했습니다!

2021-02-25 18:39 UTC, yangahh commented on order/views.py
> +        order_info.order_status_id = 2
OrderStatus라는 모델(테이블)에 해당 id에 대한 상태 명을 가지고 있어서 그걸 조건으로 걸어 객체를 가져오는 방향으로 수정하였습니다.

2021-02-25 18:39 UTC, yangahh commented on order/views.py
> +        order_info     = Order.objects.get(order_number=order_number)
네 예외처리 추가했습니다.

2021-02-25 18:40 UTC, yangahh commented on order/views.py
> +            cart_product_list.append(product_info)
네 수정하였습니다.

2021-02-25 18:42 UTC, yangahh commented on order/views.py
> +    def post(self, request, product_stock_id):
네 수정하였습니다. urls.py도 수정했습니다~

2021-02-25 18:42 UTC, yangahh commented on order/views.py
> +            cart_product_list.append(product_info)
네

2021-02-25 18:43 UTC, yangahh commented on order/views.py
> +        order_exist          = Order.objects.get(user=user, order_status_id=1)
네

2021-02-25 18:43 UTC, yangahh commented on order/urls.py
> +    path('/cart/<int:product_stock_id>', CartDetailView.as_view()),
url 모두 수정하였습니다.

2021-02-25 19:26 UTC, Kang-kyunghun requested changes

2021-02-25 19:26 UTC, Kang-kyunghun commented on order/views.py
> +        if
if 제거해 주세요.

2021-02-25 19:26 UTC, Kang-kyunghun commented on order/views.py
> +        zip_code     = address_info[0].zip_code if address_info else ""
```suggestion
        address      = address_info.first().address if address_info else ""
        zip_code     = address_info.first().zip_code if address_info else ""
```
queryset에 [0]처럼 인덱스를 직접적으로 사용하는 것은 지양하는 것이 좋습니다.

2021-02-25 19:26 UTC, Kang-kyunghun commented on order/views.py
> +        ]
```suggestion
            } for order_product in order_products]
```

2021-02-25 19:26 UTC, Kang-kyunghun commented on order/views.py
> +            return JsonResponse({"message": "DOES_NOT_EXIST"}, status=400)
마찬가지로 에러 메세지를 구분하면 좋을 것 같습니다.

2021-02-25 19:26 UTC, Kang-kyunghun commented on order/views.py
> +            return JsonResponse({"message": "DOES_NOT_EXIST"}, status=400)
에러 처리 잘 하셨습니다.
한 가지만 수정하면 더 좋을 것 같습니다.
Order가 없을 때와 OrderStatus가 없을 때의 에러 메세지가 동일 합니다. 이러면 에러가 발생 했을 때 어는 지점에서 에러가 발생 했는지 찾기가 어렵습니다.
에러 메세지를 구분하면 좋을 것 같습니다.

2021-02-25 19:26 UTC, Kang-kyunghun commented on order/views.py
> +            return JsonResponse({"message": "DOES_NOT_EXIST"}, status=400)
여기도 에러 메세지를 구분하면 좋을 것 같습니다.

2021-02-25 19:26 UTC, Kang-kyunghun commented on order/views.py
> +            return JsonResponse({"message": "DOES_NOT_EXIST"}, status=400)
에러 처리 잘 하셨습니다.
한 가지만 수정하면 더 좋을 것 같습니다.
OrderStatus가 없을 때와 ProductStock가 없을 때의 에러 메세지가 동일 합니다. 이러면 에러가 발생 했을 때 어는 지점에서 에러가 발생 했는지 찾기가 어렵습니다.
에러 메세지를 구분하면 좋을 것 같습니다.

2021-02-25 19:26 UTC, Kang-kyunghun commented on order/views.py
> +            ]
```suggestion
            cart_product_list = [{
                "category"        : order_product.product_stock.product.category.menu.name,
                "productId"       : order_product.product_stock.product.id,
                "productName"     : order_product.product_stock.product.name,
                "productSubName"  : order_product.product_stock.product.sub_name,
                "productStockId"  : order_product.product_stock.id,
                "productSize"     : order_product.product_stock.size,
                "productPrice"    : order_product.product_stock.price,
                "productStock"    : order_product.product_stock.stock,
                "productImageUrl" : order_product.product_stock.product.image_set.get(is_main=True).image_url,
                "productQuantity" : order_product.quantity
                } for order_product in order.orderproductstock_set.filter(order=order)]
```
list comprehension을 사용해서 잘 바꾸셨습니다.~~!!!!

order_products라는 변수가 한 번만 사용되고 있습니다. 이럴 경우 굳이 변수에 담지 않고 사용하는 것을 권장 합니다.

2021-02-25 19:26 UTC, Kang-kyunghun commented on order/views.py
> +            product_price = float(product_price)
```suggestion
            product_price = float(data['productPrice'])
```

2021-02-25 19:26 UTC, Kang-kyunghun commented on order/views.py
> +                shipping_cost = 5 if product_price < 20 else 0
5, 20, 0 이라는 숫자는 언제든지 바뀔 수도 있는 값입니다. 지금은 사용 된 곳이 적기 때문에 금방 수정할 수도 있지만, 만약에 사용 된 곳이 많고, 사정에 따라 자주 수정할 일이 생겼을 때 상수 처리를 하지 않았을 경우 수정에 많은 시간을 허비 할 수 있습니다.
DEFUALT_COST = 5
MINIMUM_PRICE =20
DISCOUNTED_COST =0
이런식으로 상수에 대한 변수를 만들어서 그 변수를 사용하는 것이 좋습니다.
지금 저 변수명은 예시를 들은 것이니 적절한 변수명을 사용하여 상수 처리 해주세요.

2021-02-25 19:26 UTC, Kang-kyunghun commented on order/views.py
> +                    order_number    = datetime.today().strftime("%Y%m%d") + str(randint(10000, 100000)),
고유한 상품 번호를 만들려고 하는 것으로 보입니다.
날짜를 이용해서 고유 번호를 만들려고 했던거 너무 잘 하셨습니다.
고유번호를 만드는 방법 중에 UUID라는 것이 있습니다. 
참고 해 보고 다음 프로젝트 때 사용해 봐도 좋을 것 같습니다.

2021-02-25 19:26 UTC, Kang-kyunghun commented on order/views.py
> +                order_info.shipping_cost  = 5 if order_info.sub_total_cost < 20 else 0
위에 상수 처리 수정해 주세요.

2021-02-25 19:26 UTC, Kang-kyunghun commented on order/views.py
> +
```suggestion

```
공백은 한 칸으로 해주세요.

2021-02-26 01:32 UTC, yangahh commented on order/views.py
> +        if
네 수정했습니다~

2021-02-26 01:33 UTC, yangahh commented on order/views.py
> +        zip_code     = address_info[0].zip_code if address_info else ""
넵 수정했습니다

2021-02-26 01:33 UTC, yangahh commented on order/views.py
> +            return JsonResponse({"message": "DOES_NOT_EXIST"}, status=400)
네 모두 수정했습니다~

2021-02-26 01:34 UTC, yangahh commented on order/views.py
> +            return JsonResponse({"message": "DOES_NOT_EXIST"}, status=400)
네 모두 수정했습니다~

2021-02-26 01:34 UTC, yangahh commented on order/views.py
> +            return JsonResponse({"message": "DOES_NOT_EXIST"}, status=400)
네 모두 수정했습니다~

2021-02-26 01:34 UTC, yangahh commented on order/views.py
> +            return JsonResponse({"message": "DOES_NOT_EXIST"}, status=400)
네 모두 수정했습니다~

2021-02-26 01:37 UTC, yangahh commented on order/views.py
> +            product_price = float(product_price)
수정했습니다~

2021-02-26 01:37 UTC, yangahh commented on order/views.py
> +            ]
네 수정하였습니다~

2021-02-26 01:40 UTC, yangahh commented on order/views.py
> +                    order_number    = datetime.today().strftime("%Y%m%d") + str(randint(10000, 100000)),
네 참고하겠습니다 감사합니다!

2021-02-26 01:40 UTC, yangahh commented on order/views.py
> +                shipping_cost = 5 if product_price < 20 else 0
넵

2021-02-26 01:42 UTC, yangahh commented on order/views.py
> +                order_info.shipping_cost  = 5 if order_info.sub_total_cost < 20 else 0
네~

2021-02-26 01:42 UTC, yangahh commented on order/views.py
> +
네~

2021-02-26 01:58 UTC, soheon-lee commented on order/views.py
> +
```suggestion
                defaults      = {"quantity" : 1}
            )
        

```
키가 하나밖에 없기 때문에 한 줄로 간결하게 정리하시는게 좋을 것 같아요-!

2021-02-26 01:58 UTC, soheon-lee commented on order/views.py
> +            # 장바구니에 상품이 없을 경우 order 정보 삭제
코드에 한글로 주석은 코드를 읽어내려가면서 이해하기 어려운 경우에 작성합니다.
아래 if 문은 그 의미가 명확하기 때문에, 추가적인 주석은 꼭 필요하지는 않겠네요 :)

2021-02-26 01:58 UTC, soheon-lee commented on order/views.py
> +
```suggestion
                order    = order_info,
                defaults = {'is_main': False}
            )

```
여기도 마찬가지입니다 :)

2021-02-26 02:51 UTC, yangahh commented on order/views.py
> +        ]
수정했습니다~

2021-02-26 02:53 UTC, yangahh commented on order/views.py
> +
네 수정하였습니다~

2021-02-26 03:17 UTC, yangahh commented on order/views.py
> +            # 장바구니에 상품이 없을 경우 order 정보 삭제
네

2021-02-26 03:18 UTC, yangahh commented on order/views.py
> +
네 모두 수정했습니다

2021-02-26 03:53 UTC, merged